<a href="https://colab.research.google.com/github/aymen-cyber/Text_process/blob/main/workinOnTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([[0, 10, 20],
                 [20, 30, 40],
                 [30, 50, 60]])
b = tf.constant([5, 5, 5])
print( a+ b )
print( tf.add(a,b) )
print( (3*a) )

tf.Tensor(
[[ 5 15 25]
 [25 35 45]
 [35 55 65]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 5 15 25]
 [25 35 45]
 [35 55 65]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[  0  30  60]
 [ 60  90 120]
 [ 90 150 180]], shape=(3, 3), dtype=int32)


In [3]:
tf.reduce_min(a , axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 0, 20, 30], dtype=int32)>

In [4]:
tf.argmax(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 2])>

In [ ]:
tf.equal("bONJOUR","bonjour")

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [ ]:
a = tf.constant([3, 5, 3, 8])
tf.unique(a)
# reduce redandence

Unique(y=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 8], dtype=int32)>, idx=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 0, 2], dtype=int32)>)

In [ ]:
reduce_simple_1 = tf.constant([1,2,3,4,5,6], shape=[2,3])
print("original data", reduce_simple_1.numpy())

original data [[1 2 3]
 [4 5 6]]


In [ ]:
tf.reduce_sum(reduce_simple_1, axis=None).numpy()
tf.reduce_prod(reduce_simple_1, axis=None).numpy()

720

In [ ]:
tf.reduce_sum(reduce_simple_1, axis=0).numpy()
tf.reduce_sum(reduce_simple_1, axis=1).numpy()

array([ 6, 15], dtype=int32)

In [ ]:
a = tf.constant([True, False, True, False], shape=[2, 2])
tf.reduce_all(a)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [ ]:
a = tf.constant([True, True, False, False], shape=[2, 2])
tf.reduce_all(a, axis=1)
tf.reduce_all(a, axis=0)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False, False])>

In [ ]:
concat_simple_1 = tf.random.normal([100,100,3])
concat_simple_2 = tf.random.normal([100,100,3])
print(concat_simple_1.shape)
print(concat_simple_2.shape)
print(tf.concat([concat_simple_1, concat_simple_2], axis= 0).shape)
print(tf.concat([concat_simple_1, concat_simple_2], axis= 1).shape)

(100, 100, 3)
(100, 100, 3)
(200, 100, 3)
(100, 200, 3)


In [ ]:
print(tf.stack([concat_simple_1, concat_simple_2], axis= 0).shape)
print(tf.stack([concat_simple_1, concat_simple_2], axis= 1).shape)
print(tf.stack([concat_simple_1, concat_simple_2], axis= -1).shape)
print(tf.stack([concat_simple_1, concat_simple_2], axis= 2).shape)

(2, 100, 100, 3)
(100, 2, 100, 3)
(100, 100, 3, 2)
(100, 100, 2, 3)


In [ ]:
a = tf.constant([[0, 0, 0],
                 [1, 1, 1],])
b = tf.constant([[5, 5, 5],
                 [2, 2, 2]])

print(a)
print(b)
print(tf.concat([a, b], axis= 0))
print(tf.concat([a, b], axis= 1))

tf.Tensor(
[[0 0 0]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[5 5 5]
 [2 2 2]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [1 1 1]
 [5 5 5]
 [2 2 2]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[0 0 0 5 5 5]
 [1 1 1 2 2 2]], shape=(2, 6), dtype=int32)


In [ ]:
print(tf.stack([a, b], axis= 0))
print(tf.stack([a, b], axis= 1))
print(tf.stack([a, b], axis= -1))
print(tf.stack([a, b], axis= 2))

tf.Tensor(
[[[0 0 0]
  [1 1 1]]

 [[5 5 5]
  [2 2 2]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[0 0 0]
  [5 5 5]]

 [[1 1 1]
  [2 2 2]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[0 5]
  [0 5]
  [0 5]]

 [[1 2]
  [1 2]
  [1 2]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[0 5]
  [0 5]
  [0 5]]

 [[1 2]
  [1 2]
  [1 2]]], shape=(2, 3, 2), dtype=int32)


In [ ]:
import numpy as np

split1 = tf.random.normal([10, 100, 100, 3])
splited1 = tf.split( split1, num_or_size_splits=5, axis=0)
np.shape(splited1)

(5, 2, 100, 100, 3)

In [ ]:
splited2 = tf.split( split1, num_or_size_splits=[3, 5, 2], axis=0)
print(np.shape(splited1), np.shape(splited1)[0], np.shape(splited1)[1], np.shape(splited1)[2])

(5, 2, 100, 100, 3) 5 2 100


In [ ]:
sort1 = tf.random.shuffle(tf.range(10))
print( sort1.numpy() )

[7 9 5 1 3 0 6 4 2 8]


In [ ]:
sorted1 = tf.sort(sort1, direction="ASCENDING")
sorted1 = tf.sort(sort1, direction="DESCENDING")
sorted1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [ ]:
argsorted1 = tf.argsort(sort1, direction="DESCENDING")
argsorted1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 9, 0, 6, 2, 7, 4, 8, 3, 5], dtype=int32)>

In [ ]:
#Eager execution : tensorflow 2.x
x = tf.ones((2, 2), dtype= tf.dtypes.float32)
y = tf.constant([[1, 2],[3, 4]], dtype= tf.dtypes.float32)
z = tf.matmul(x, y)
z

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 6.],
       [4., 6.]], dtype=float32)>

In [ ]:
import tensorflow.compat.v1 as tf1

In [ ]:
# computational graph. Tensorflow 1.x
tf1.disable_eager_execution()
# Create a graph and designe it as 
a = tf1.ones((2, 2), dtype= tf.dtypes.float32)
b = tf1.constant([[1, 2],[3, 4]], dtype= tf.dtypes.float32)
c = tf1.matmul(a, b)
c

<tf.Tensor 'MatMul:0' shape=(2, 2) dtype=float32>

In [ ]:
with tf1.Session() as sess:
  print(sess.run(c))

[[4. 6.]
 [4. 6.]]


In [ ]:
@tf.function
def NetCalculation(inputs, w, b):
  x = tf.zeros(inputs[0].shape, dtype= tf.dtypes.int32)
  for i in inputs:
    x= tf.add(x, i*w)
  return tf.add(x, -b)

In [ ]:
NetCalculation(a , 3, a[0])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([150, 260, 340], dtype=int32)>

In [ ]:
x = tf.zeros(a[0].shape, dtype= tf.dtypes.int32)
for i in a:
  x= tf.add(x, i*3)
print(tf.add(x, -a[0]))

tf.Tensor([150 260 340], shape=(3,), dtype=int32)
